### ISSUE TITLE
Message handler with custom method

### ISSUE THREAD

**Issue by marcelomx** [SimpleBus/MessageBus#25]
In the SymfonyBridge http://simplebus.github.io/SymfonyBridge/doc/command_bus_bundle.html, the service configuration for message handler brings the possibility to use a custom `handle` method. 

```
services:
    register_user_command_handler:
        ...
        tags:
            - { name: command_handler, handles: ..., method: registerUser }
```

This is great. This way, we have a class handler that could have different methods to handle different messages (like a controller). Another implication is the type hint, that is more verbosity. E.g:

```
class TodoHandler implements MessageHandler
{
  public function createTodo(CreateTodoMessage $message) {}
  public function removeTodo(RemoveTodoMessage $message) {}
}

```

But, its not working. :(

Another issue is that the bus forces the class handler to implements the `MessageHandler` interface and the `handle` method. In other words, the class handler needs to have the custom handle method and the original `handle` method implemented. 

```
class TodoHandler implements MessageHandler
{
  public function createTodo(CreateTodoMessage $message) {}
  public function removeTodo(RemoveTodoMessage $message) {}
  public function handle(Message $message) {}
}

```
