### ISSUE TITLE
Create CommandBus and EventBus interfaces that extend MessageBus

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/MessageBus#73]
One thing that I don't like about this awesome lib is that it forces me to write `MessageBus $commandBus` every single time.

Would it be possible to have a `CommandBus` and `EventBus` in some way?

**Comment by ruudk** [comment]
It would also be very handy for Symfony 3.3 Auto-Wire.

**Comment by cmodijk** [comment]
> Would it be possible to have a `CommandBus` and `EventBus` in some way?

That would mean that we need to create separate classes just for a naming thing? For example;

```php
namespace SimpleBus\Message\Bus\Middleware;

use SimpleBus\Message\Bus\CommandBus;

class CommandBusSupportingMiddleware extends MessageBusSupportingMiddleware implements CommandBus
{
}
```

```php
namespace SimpleBus\Message\Bus\Middleware;

use SimpleBus\Message\Bus\EventBus;

class EventSupportingMiddleware extends MessageBusSupportingMiddleware implements EventBus
{
}
```

```php
namespace SimpleBus\Message\Bus;

interface CommandBus extends MessageBus
{
}
```

```php
namespace SimpleBus\Message\Bus;

interface EventBus extends MessageBus
{
}
```

> It would also be very handy for Symfony 3.3 Auto-Wire.

I'm stil not that familiar with the Auto-Wire feature is my example correct that it would help the auto-wire feature?

**Comment by ruudk** [comment]
> That would mean that we need to create separate classes just for a naming thing? For example;

`just for a naming thing` > it's really good for clarity, and developer experience :) 

This is how I fixed it myself:

```php
<?php

namespace MyNamespace\Api\FrameworkBundle\SimpleBus;

use SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware;

class CommandBus extends MessageBusSupportingMiddleware
{

}

```

```php
<?php

namespace MyNamespace\Api\FrameworkBundle\SimpleBus;

use SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware;

class EventBus extends MessageBusSupportingMiddleware
{

}
```

```php
<?php

namespace MyNamespace\Api\FrameworkBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use MyNamespace\Api\FrameworkBundle\SimpleBus\CommandBus;
use MyNamespace\Api\FrameworkBundle\SimpleBus\EventBus;

class SimpleBusCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $container->getDefinition('simple_bus.command_bus')->setClass(CommandBus::class);
        $container->getDefinition('simple_bus.event_bus')->setClass(EventBus::class);
    }
}

```

Then I can just include my dependency in my controller:
```php
<?php

namespace MyNamespace\Api\Controller;

class MyController
{
    /**
     * @var CommandBus
     */
    private $commandBus;

    public function __construct(CommandBus $commandBus)
    {
        $this->commandBus  = $commandBus;
    }
}
```

This is how the auto wire is set-up:
```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MyNamespace\Api\:
        resource: '../../*'
        exclude: '../../{Entity,Model,Tests}'

    MyNamespace\Api\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    MyNamespace\Api\Handler\:
        resource: '../../Handler'
        public: true
        tags:
            - { name: command_handler }

```

**Comment by ruudk** [comment]
And yes, your example would work with auto-wire :)

**Comment by cmodijk** [comment]
Is this something for the [MessageBus](https://github.com/SimpleBus/MessageBus) or more a nice to have feature for [SymfonyBridge](https://github.com/SimpleBus/SymfonyBridge). The `MessageBus` does not care about `autowire` feature and having 2 classes to just extend something for a naming think seems a bit weird to me. 

But from the symfony point of few we do care about `autowire` so maybe we should make these alias classes there?

**Comment by ruudk** [comment]
You're right :) It might be better to handle over there.

**Comment by holtkamp** [comment]
Also encountered this while using [PHP-DI](http://php-di.org/) as DependencyInjectionContainer. Autowiring will break, but annotation-based injection works:

```php
    /**
     * @Inject("CommandBus")
     *
     * @var \SimpleBus\Message\Bus\MessageBus
     */
    private $commandBus;
```

or when having both a synchronous and an asynchronous CommandBus, this can be used:

```php
    /**
     * @Inject("SynchronousCommandBus")
     *
     * @var \SimpleBus\Message\Bus\MessageBus
     */
    private $commandBus;
```

>having 2 classes to just extend something for a naming think seems a bit weird to me.

Agree with this, this should take place in "bridge" or in userland code... 

off-topic: I am still in doubt which way of dependency injection is preferred. The annotation-based injection, or constructor-based injection. [this guide](http://php-di.org/doc/best-practices.html) kind of hints to the constructor based approach. Only in that case, 'empty' classes will need to be used just to have this working. The clean approach of SimpleBus seems to be an exception though, but always nice to hear how others deal with this.

**Comment by cmodijk** [comment]
@ruudk Can you make a pull request for this in the symfony bridge?

**Comment by ruudk** [comment]
Done

https://github.com/SimpleBus/AsynchronousBundle/pull/15 https://github.com/SimpleBus/SymfonyBridge/pull/52

**Comment by garak** [comment]
I'm also interested in using autowiring with Symfony 3.3, but I'm not sure about a couple of things:
* why we need an extra class? Can't you just add an alias for `MessageBusSupportingMiddleware`? 
* how do you pass the `handles` option to services tagged with `command_handler`?

**Comment by ruudk** [comment]
> why we need an extra class? Can't you just add an alias for MessageBusSupportingMiddleware?
How do you autowire it then? It requires config if you want to use aliases.

> how do you pass the handles option to services tagged with command_handler?
This is done by the AutoRegister compiler pass :) See https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/Compiler/AutoRegister.php

**Comment by garak** [comment]
thanks @ruudk but I can't make it working :disappointed: 
I keep getting `The attribute "handles" of tag "command_handler" of service "MyNS\FooHandler" is mandatory ` error.
I even tried to debug the AutoRegister.php class and the `$tags` variable is an empty array, like if the tag were missing.
Here is my conf:
```yaml
services:
   _defaults:
       autowire: true
       autoconfigure: true
       public: false

   MyNs\:
       resource: '%kernel.project_dir%/src/MyNs'
       public: true
       tags: ['command_handler']
```
